### ISSUE TITLE
Uncaught Error: Call to undefined method GoogleTranslate::str_to_dom() 

### ISSUE THREAD

**Issue by NightMachinery** [vielhuber/stringhelper#1]
I am trying to get your Google Translate script to work. But I get the following error:
```
❯ php /Users/evar/scripts/phplang/gtranslate/gtranslate.php
PHP Deprecated:  Return type of __empty_helper::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/evar/scripts/phplang/gtranslate/vendor/vielhuber/stringhelper/src/functions.php on line 1481

Deprecated: Return type of __empty_helper::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/evar/scripts/phplang/gtranslate/vendo
r/vielhuber/stringhelper/src/functions.php on line 1481
PHP Fatal error:  Uncaught Error: Call to undefined method GoogleTranslate::str_to_dom() 
in /Users/evar/scripts/phplang/gtranslate/gtranslate.php:47
Stack trace:
#0 /Users/evar/scripts/phplang/gtranslate/gtranslate.php(11): GoogleTranslate->parseResultPre('This is a jungl...')
#1 /Users/evar/scripts/phplang/gtranslate/gtranslate.php(287): GoogleTranslate->translate('This is a jungl...')
#2 {main}
  thrown in /Users/evar/scripts/phplang/gtranslate/gtranslate.php on line 47

Fatal error: Uncaught Error: Call to undefined method GoogleTranslate::str_to_dom() in /Users/evar/scripts/phplang/gtranslate/gtranslate.php:47
Stack trace:
#0 /Users/evar/scripts/phplang/gtranslate/gtranslate.php(11): GoogleTranslate->parseResultPre('This is a jungl...')
#1 /Users/evar/scripts/phplang/gtranslate/gtranslate.php(287): GoogleTranslate->translate('This is a jungl...')
#2 {main}
  thrown in /Users/evar/scripts/phplang/gtranslate/gtranslate.php on line 47
```

Here is my fork of your script: https://github.com/NightMachinary/.shells/tree/master/scripts/phplang/gtranslate

**Comment by vielhuber** [comment]
Hello!

Please first install needed dependencies (if not yet done):

```sh
composer require fzaninotto/faker vielhuber/stringhelper
```

Then fix the few lines of code as seen in this revision:

https://gist.github.com/vielhuber/b7739bf50b2edcf636c43a8f8910def9/revisions#diff-13c8070b20b0c3271f899b6381691ae2604aecb086fb2a01fd7f99f08ff70fbe

Then this should be a good base for your further work.
